version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: zaychik_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: zaychik_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: zaychik_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@zaychik.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend
    container_name: zaychik_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: zaychik_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
