spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/zaychik_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update # Важно! Используем create-drop для первого запуска
    show-sql: true
    properties:
      jakarta:
        persistence:
          exclude-unlisted-classes: true
      hibernate:
        archiver:
          scanner:
            excludes: java.**,javax.**,jakarta.**
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jakarta.persistence.schema-generation.database.action: none
logging:
  level:    
    org:
      springframework:
        web:
          socket:
            messaging: TRACE
        messaging:
          simp:
            stomp: TRACE
      hibernate:
        type:
          descriptor:
            sql: TRACE